name: CI DevSecOps

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  sast-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install SAST tools
        run: |
          pip install semgrep bandit

      - name: Run Bandit
        run: |
          bandit -r backend-api scraping-service analysis-service publishing-service || true

      - name: Run Semgrep
        run: |
          semgrep --config p/ci || true

      # ---------- FASE 4: TEST - PRUEBAS UNITARIAS ----------
      - name: Install backend dependencies + pytest
        working-directory: ./backend-api
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run backend pytest
        working-directory: ./backend-api
        run: |
          pytest

      # ---------- BUILD + TRIVY (FASE 3, lo que ya tenías) ----------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./backend-api
          tags: backend-api:ci-latest
          load: true
          push: false

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "backend-api:ci-latest"
          ignore-unfixed: true
          vuln-type: "os,library"
          format: "table"
          exit-code: "0"

      # ---------- FASE 4: TEST - DAST CON OWASP ZAP ----------
      - name: Start backend in staging mode
        working-directory: ./backend-api
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 10

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
            target: 'http://localhost:8000'
            allow_issue_writing: false     # para que no crea Issues
            fail_action: false             # para que no falla el job por findings
            artifact_name: zap-scan        # se cambia por nombre válido para el artifact
